### ISSUE TITLE
[FEATURE] GetPatientsByDoctorAndDay

### ISSUE THREAD

**Issue by margarcac1** [FIS2425/authorization-svc#56]
## Feature Description

This feature would allow retrieving a list of patients scheduled for a specific doctor on a given day.

## Definition of Done

- [ ] Returns a list of patients associated with the specified doctor and date.

**Comment by AntonioRodriguezRuiz** [comment]
@margarcac1 is this meant for this repository?

**Comment by margarcac1** [comment]
Discarded task
