### ISSUE TITLE
Create user

### ISSUE THREAD

**Issue by AntonioRodriguezRuiz** [FIS2425/authorization-svc#7]
## Feature Description

As I clinic admin I want to create users so that patients and doctors can use the app of the clinic 

## Definition of Done

- [x] Determine who can create users to be in line with the rest of people
- [x] Implement function happy path
- [x] Implement error messages:
  - [x] 400
  - [x] 401 & 403 (If only clinic admins can add users)
- [ ] #8
- [x] Add OpenAPI docs

**Comment by alvgonfri** [comment]
Users will be created by a clinic admin.
